### ISSUE TITLE
Remove values from contracted 'amount awarded' facet if zero grants match

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/grantnav#245]

**Comment by robredpath** [comment]
It might make more sense to only remove from the top and bottom where there are 0s, so in the case of (0)(0)(9)(0)(9)(0)(0) it would become (9)(0)(9)

**Comment by morchickit** [comment]
@robredpath - I think this is fixed but I can't see the image. Can you help with this?

**Comment by robredpath** [comment]
<img width="281" alt="Screenshot 2020-05-18 at 16 46 43" src="https://user-images.githubusercontent.com/641009/82232962-375f7b00-9927-11ea-859d-44c9412ee6f8.png">

**Comment by mariongalley** [comment]
Looks like this is either not fixed or has been rolled back:
![image](https://user-images.githubusercontent.com/82958988/137450693-ed28fb01-82a2-478c-9e6e-26273d0394c2.png)

**Comment by robredpath** [comment]
Interesting. I wonder if we lost something during the new facet design last year. 

Now that we've got scrollbars instead of "see more", I'm not sure how relevant this is. But, I'm also sure we can fix it if we want to!

**Comment by mariongalley** [comment]
Yeah I'm not sure if the fact it's a scroll bar and you can see more values at once eliminates the need to truncating the options from the top / bottom where they're 0.
