### ISSUE TITLE
Persistence of district URI (for example)

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/grantnav#368]
I'd have concerns in terms of how we format the URIs for district pages - for example:

http://grantnav.threesixtygiving.org/district/Manchester%20District%20(B)

Here - we include the terms District and (B), plus whitespace

My concern is that this isn't too "restful" (difficult for me to manipulate the URL to get other districts)  It may be more straightforward to use the E0 code for the URI, as that is consistent and unique?

@Bjwebb may have opinions (remember how we did this with Plings?)

**Comment by stevieflow** [comment]
This is discussed by @timgdavies in https://github.com/OpenDataServices/grantnav/issues/383 

> Provide a URL alias for http://grantnav.threesixtygiving.org/district/Birmingham%20District%20(B) of http://grantnav.threesixtygiving.org/geo/E08000025 or similar?

**Comment by stevieflow** [comment]
(adding data access label, as we coudl also imagine how .json could be added to such URLs, for access to raw data)

**Comment by morchickit** [comment]
Can we close this? I thought we fixed the admingeo with a B ages ago.. @stevieflow @robredpath

**Comment by stevieflow** [comment]
True that we got rid of the B, but the issue still persists (sorry!) imho:

https://grantnav.threesixtygiving.org/district/Exeter%20District

My original post was to ask to look at the URL for a district being based on the code rather than the name, so that they can more easily be manipulated (for example)

So /E07000041 instead of /Exeter%20District in this example

**Comment by morchickit** [comment]
Got it. Keeping this now.
